doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            intangible_id: App\Things\Intangibles\Infrastructure\Persistence\Doctrine\Mappings\IntangibleIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Things\Intangibles\:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/../../src/Things/Intangibles/Infrastructure/Persistence/Doctrine/Mappings'
                prefix: 'App\Things\Intangibles\Domain'
