services:
    head:
        container_name: head
        user: "${USER_ID}:${GROUP_ID}"
        build:
            context: .
        restart: unless-stopped
        volumes:
            - .:/app:delegated
    api:
        container_name: api
        user: "${USER_ID}:${GROUP_ID}"
        build:
            context: .
        command: "symfony server:start --dir=apps/api/public --port=8080 --allow-http --no-tls --allow-all-ip"
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - .:/app:delegated
    sql:
        container_name: sql
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
            POSTGRES_USER: ${POSTGRES_USER:-root}
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - .docker/pgsql/data:/var/lib/postgresql/data:rw
    no-sql:
        container_name: no-sql
        image: mongo:${MONGO_VERSION:-7}
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
