parameters:
    context.root_path: '../../../../../..'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Authorization\SignIn\:
        resource: '%context.root_path%/src/Authorization/SignIn/{Application,Domain,Infrastructure}/*'
    authorization.signin.google.client:
        class: App\Authorization\SignIn\Infrastructure\Providers\Google\GoogleClient
        arguments:
            $config: '%env(json:GOOGLE_AUTH_CONFIG)%'
