doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App\Inventory\Products\:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/../../src/Inventory/Products/Infrastructure/Persistence/Doctrine/Mappings'
        prefix: 'App\Inventory\Products\Domain'
