imports:
    - {resource: products_doctrine.yaml}
parameters:
    context.root_path: '../../../../../..'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    Techpump\Inventory\Products\:
        resource: '%context.root_path%/src/Inventory/Products/{Application,Domain,Infrastructure}/*'
