imports:
  - { resource: carts_doctrine.yaml }
parameters:
  context.root_path: '../../../../../..'
services:
  _defaults:
    autowire: true
    autoconfigure: true
  _instanceof:
    App\Shared\Domain\Bus\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: command.bus }
    App\Shared\Domain\Bus\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: query.bus }
  App\Shop\Carts\:
    resource: '%context.root_path%/src/Shop/Carts/{Application,Domain,Infrastructure}/*'
  App\Shop\Carts\Domain\CartRepository: '@App\Shop\Carts\Infrastructure\Persistence\DoctrineAllCartRepository'
  App\Inventory\Products\Domain\ProductRepository: '@App\Inventory\Products\Infrastructure\Persistence\DoctrineProductRepository'
  App\Shop\Carts\Application\AddProduct\AddProductToCartCommandHandler:
    arguments:
      $activeCartRepository: '@App\Shop\Carts\Infrastructure\Persistence\DoctrineActiveCartRepository'
  App\Shop\Carts\Application\UpdateProduct\UpdateProductCartCommandHandler:
    arguments:
      $activeCartRepository: '@App\Shop\Carts\Infrastructure\Persistence\DoctrineActiveCartRepository'
  App\Shop\Carts\Application\RemoveProduct\RemoveProductCartCommandHandler:
    arguments:
      $activeCartRepository: '@App\Shop\Carts\Infrastructure\Persistence\DoctrineActiveCartRepository'
  App\Shop\Carts\Application\Pay\PayCartCommandHandler:
    arguments:
      $activeCartRepository: '@App\Shop\Carts\Infrastructure\Persistence\DoctrineActiveCartRepository'
