imports:
    - {resource: carts_doctrine.yaml}
parameters:
    context.root_path: '../../../../../..'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Techpump\Shared\Domain\Bus\Command\CommandHandler:
            tags:
                - {name: messenger.message_handler, bus: command.bus}
        Techpump\Shared\Domain\Bus\Query\QueryHandler:
            tags:
                - {name: messenger.message_handler, bus: query.bus}
    Techpump\Shop\Carts\:
        resource: '%context.root_path%/src/Shop/Carts/{Application,Domain,Infrastructure}/*'
    Techpump\Shop\Carts\Domain\CartRepository: '@Techpump\Shop\Carts\Infrastructure\Persistence\DoctrineAllCartRepository'
    Techpump\Inventory\Products\Domain\ProductRepository: '@Techpump\Inventory\Products\Infrastructure\Persistence\DoctrineProductRepository'
    Techpump\Shop\Carts\Application\AddProduct\AddProductToCartCommandHandler:
        arguments:
            $activeCartRepository: '@Techpump\Shop\Carts\Infrastructure\Persistence\DoctrineActiveCartRepository'
    Techpump\Shop\Carts\Application\UpdateProduct\UpdateProductCartCommandHandler:
        arguments:
            $activeCartRepository: '@Techpump\Shop\Carts\Infrastructure\Persistence\DoctrineActiveCartRepository'
    Techpump\Shop\Carts\Application\RemoveProduct\RemoveProductCartCommandHandler:
        arguments:
            $activeCartRepository: '@Techpump\Shop\Carts\Infrastructure\Persistence\DoctrineActiveCartRepository'
    Techpump\Shop\Carts\Application\Pay\PayCartCommandHandler:
        arguments:
            $activeCartRepository: '@Techpump\Shop\Carts\Infrastructure\Persistence\DoctrineActiveCartRepository'
