parameters:
  context.root_path: '../../../../..'
services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\Shared\:
    resource: '%context.root_path%/src/Shared/{Application,Domain,Infrastructure}/*'
  App\Shared\Infrastructure\Framework\Symfony\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onException }
  App\Shared\Infrastructure\Framework\Symfony\ApiController:
    arguments:
      $commandBus: '@command.bus'
      $queryBus: '@query.bus'
