imports:
  - { resource: ../../../src/Shared/Infrastructure/DependencyInjection/Symfony/shared_services.yaml }
  - { resource: ../../../src/Things/Intangibles/Infrastructure/Symfony/DependencyInjection/intangibles_services.yaml }
  - { resource: ../../../src/Authorization/SignIn/Infrastructure/Symfony/DependencyInjection/signin_services.yaml }
