imports:
  - { resource: ../../../src/Shared/Infrastructure/Symfony/DependencyInjection/shared_services.yaml }
  - { resource: ../../../src/Things/Intangibles/Infrastructure/Symfony/DependencyInjection/intangibles_services.yaml }
