imports:
  - { resource: ../../../src/Shared/Infrastructure/Symfony/DependencyInjection/shared_services.yaml }
  - { resource: ../../../src/Things/Intangibles/Infrastructure/Symfony/DependencyInjection/intangibles_services.yaml }
parameters:
  app.root_path: '../../..'
  app.app_path: '/apps/head'
  app.app_path_from_root: '%app.root_path%%app.app_path%'
services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  App\Apps\Head\:
    resource: '%app.app_path_from_root%/src/'
    exclude: '%app.app_path_from_root%/src/{Entity/,Controller/,Migrations/,DependencyInjection/,Kernel.php}'
